version: '3'
services:
    ap:
        build: .
        command: bundle exec rails s
        volumes:
            - .:/myapp
            - public-data:/myapp/public
            - tmp-data:/myapp/tmp
        depends_on:
            - db
        tty: true
    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
            - db-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: "Asia/Tokyo"
        ports:
            - "3306:3306"
    web:
      build: ./nginx
      volumes:
        - public-data:/myapp/public
        - tmp-data:/myapp/tmp
      ports:
        - 80:80
      depends_on:
        - ap
volumes:
    db-volume:
    public-data:
    tmp-data:
